config/routes.rb
Rails.application.routes.draw do
  # overwrite the url path name for sessions
  # change to use self defined registration controller
  devise_for :users, skip: :registrations, path: '',
             path_names: {sign_in: 'login',
                          sign_out: 'logout',
                          sign_up:'register',
             },
             controllers: {registrations: 'registrations'}

  # set the prefix of the path so that we can rename the path helper method
  ## BECAREFUL, USE :user insteand :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
    post 'login', to: 'devise/sessions#create'
    delete 'logout', to: 'devise/sessions#destroy', as: :logout
    # create user has the same path name as
    get 'register', to: 'registrations#new', as: :register
    post 'register', to: 'registrations#create'
    post '/', to: 'store#index'

  end

  # have declare the products routes before the locale enabled routes
  # otherwise /products will be interpreted as /(:locale) and the root controller will handle the request
  # instead of products controller
  resources :products do
    get :who_bought, on: :member
  end
  # for current user
  get 'users/profile', to: 'users#show_current_user', as: :current_user
  get 'users/edit', to: 'users#edit', as: :edit_current_user
  patch 'users/profile', to: 'users#update', as: :update_current_user
  # for future admin access
  get 'users/:id', to: 'users#show', as: :user
  get 'users', to: 'users#index', as: :users

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: :store_index, via: :all
  end


  # serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PragProg Books Online Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
    
    <!--set locale for i18n-js-->
    <script type="text/javascript" charset="utf-8">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>"
    </script>
  </head>

  <body>

    <header class="main">
      <aside>
        <%= form_tag store_index_path, class: 'locale' do %>
          <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
          <%= submit_tag 'submit', id: 'submit_locale_change' %>
        <% end %>
      </aside>

      <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
      <h1><%= @page_title %></h1>
    </header>

    <section class="content">
      <nav class="side_nav">
        <div id="cart" class="carts">
          <%= render_if(@cart && @cart.line_items.any?) {render(partial: 'carts/cart', locals: {cart: @cart})} %>
        </div>
        <ul>
          <li><a href="/"><%= t('.home') %></a></li>
          <li><a href="/questions"><%= t('.questions') %></a></li>
          <li><a href="/news"><%= t('.news') %></a></li>
          <li><a href="/contact"><%= t('.contact') %></a></li>
          <% if !user_signed_in? %>
            <%= button_to 'Login', login_path, method: :get %>
          <% end %>

        </ul>
      </nav>
      
      <% if user_signed_in? %>
          <nav class="logged_in_nav">
            <ul>
              <li><%= link_to 'Orders', orders_path %></li>
              <li><%= link_to 'Products', products_path %></li>
              <li><%= link_to 'Users', users_path %></li>
              <li><%= button_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </nav>
      <% end %>
      
      <main class='<%= controller.controller_name %>'>
        <% if notice %>
            <aside id="notice"><%= notice %></aside>
            <aside id="alert"><%= alert %></aside>
        <% end %>
        <%= yield %>
      </main>
    </section>

  </body>
</html>